name: Generate Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Docs
        run: |
          # Create run-specific folder
          RUN_DIR="output/${GITHUB_RUN_ID}"
          mkdir -p $RUN_DIR

          # Run doxygen
          doxygen Doxyfile

          # Move generated HTML to run-specific folder
          mv output/html/* $RUN_DIR/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - id: deploy
        uses: actions/deploy-pages@v4

      - name: Show Unique Docs URL
        run: |
          echo "Docs deployed for this run at:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.repository }}/$GITHUB_RUN_ID/"