name: Generate Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Docs
        run: doxygen Doxyfile

      - name: Prepate versioned docs
        run: |
          mkdir -p output/html/${{ github.run_id }}
          mv output/html/* output/html/${{ github.run_id }}/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/html

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest

    environment:
      name: github-pages_${{ github.run_id }}
      url: ${{ steps.deploy.outputs.page_url }}/${{ github.run_id }}

    steps:
      - name: Deploy to Pages
        id: deploy
        uses: actions/deploy-pages@v4